import { getLayout } from '@components/layout/layout';
import { GetStaticProps } from 'next';

export default function TermsPage() {
return (
  <>
    <div
    className="flex items-center justify-center pt-4 pb-20 px-6 md:px-20 lg:px-32 xl:px-40 2xl:px-48 md:py-20"
    style={{
      backgroundImage: 'url("/assets/images/homepage/policies-page-background-v1.png")',
      backgroundSize: 'cover',
      backgroundPosition: 'top',
      backgroundAttachment: 'fixed',
      position: 'relative',
    }}
  >
    <div
        style={{
          position: 'absolute', // Position absolutely to cover the parent
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
          backdropFilter: 'blur(10px)', // Apply the blur effect
        }}
      ></div>
      <div style={{ position: 'relative', zIndex: 1 }}>
      <div>
      <h2 className="text-[#535BA3] text-center font-bold mt-10 mb-4 text-4xl sm:text-5xl md:text-6xl">
          TERMS OF SERVICE
        </h2>

        <p className="text-gray-700 mb-4">Welcome to Thriftmark!
        <br /><br />Thriftmark Lifestyles Private Limited (as applicable, “Thriftmark”, “Company”, “we,” “us,” and/or “our”) provides its services (described below) to you through its mobile applications and other software made available by Thriftmark and its websites located at www.Thriftmark.in (collectively, the “Service(s)”), subject to the following Terms of Service (as amended from time to time, these “Terms”). We reserve the right, at our sole discretion, to change or modify portions of these Terms at any time without further notice. You should periodically visit this page to review the current Terms so you are aware of any revision to which you are bound and print a copy of these Terms for your records. If we do this, we will post the changes to these Terms on this page and will indicate at the top of this page the date these terms were last revised. We may also notify you, either through the Services user interface, in an email notification or through other reasonable means. Any such changes will become effective for existing users no earlier than ten (10) days after they are posted, except that changes addressing new functions of the Services or changes made for legal reasons will be effective immediately. Your continued use of the Service after the date any such changes become effective constitutes your acceptance of the new Terms. If you do not agree to abide by these or any future Terms, do not use or access (or continue to use or access) the Service.</p>
        <p className="text-gray-700 font-bold mb-4">PLEASE READ THESE TERMS CAREFULLY AS THEY CONTAIN AN AGREEMENT TO ARBITRATE AND OTHER IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES AND OBLIGATIONS.  THE  AGREEMENT  TO  ARBITRATE  REQUIRES  (WITH  LIMITED  EXCEPTION) THAT YOU SUBMIT CLAIMS YOUHAVE AGAINST US TO BINDING AND FINAL ARBITRATION, AND FURTHER (1) YOU WILL ONLY BE PERMITTED TO PURSUE CLAIMS AGAINST COMPANY ON AN INDIVIDUAL BASIS, NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE ACTION OR PROCEEDING, AND (2) YOU WILL ONLY BE PERMITTED TO SEEK  RELIEF  (INCLUDING  MONETARY,  INJUNCTIVE,  AND  DECLARATORY  RELIEF)  ON  AN INDIVIDUAL BASIS. PLEASE INDICATE YOUR ACCEPTANCE TO THESE TERMS IN ACCORDANCE WITH  THE  INSTRUCTIONS  PROVIDED  BY  THRIFTMARK.  INDICATING  ACCEPTANCE ESTABLISHES  A  BINDING  AND  EXECUTED  WRITTEN  AGREEMENT  BETWEEN  YOU  AND THRIFTMARK. IF YOU DO NOT ACCEPT THESE TERMS, YOU CANNOT USE THE SERVICE.</p>

        <p className="text-gray-700 mb-4">The  Terms  include,  and  incorporate  by  reference,  the  following  policies:  the  Thriftmark Privacy Policy and the Fee Policy.</p>
        
        <h3 className="text-[#535BA3] font-semibold mt-5 mb-2 text-xl md:text-3xl">ACCESS AND USE OF THE SERVICE</h3>
        <p className="text-gray-700 mb-4"><b>Services Description:</b> The  Service  is  a  technology  platform  that  provides  an  online  social marketplace  in  which  consumers  and  boutiques  can  list  and  sell  their clothes/fashion/accessories/unique  items  (“Items”),  and  buyers  can  browse  and  purchase Items. Users who purchase Items through the Service are “Buyers,” and users who list and sell Items through the Service are “Sellers.” A user may be both a Buyer and Seller. All purchases are made directly (and any contract for purchase and sale is) between the Buyer and the Seller;  Thriftmark  is  not  a  traditional  auctioneer,  nor  Thriftmark  may  facilitate  storage, dispatch, and pricing assistance for certain sellers that wish to sell multiple goods in bulk in return  for  a  fee.  The  Service  includes  pricing  and  listing  assistance  and  shipping,  but  not buying or selling. We may also help facilitate the resolution of disputes between our Buyers and Sellers, but, Thriftmark has no control over and does not guarantee (a) the existence, quality, safety, authenticity, or legality of Items advertised on the Service; (b) the truth or accuracy of Sellers’ content or listings on the Service; (c) the ability of Sellers to sell Items through the Service and ship Items within required shipping windows; (d) the ability of Buyers to pay for Items purchased through the Service; or (e) that a Buyer or Seller will actually complete  a  transaction,  effectuate  trouble-free  delivery  and  shipping,  or  return  an  Item through the Service.</p>
        <p className="text-gray-700 mb-4"><b>Third  Party  Services:</b> You  may  register  for  the  Service  using  third  party  services  (e.g., Facebook Connect) and otherwise enable various third party services to be directly integrated into your Thriftmark experience. By directly integrating these services into the Service, we make  your  online  experiences  richer  and  more  personalized.  To  take  advantage  of  these features, we may ask you to register for or log into such services on the websites of their respective providers. By enabling third party services within the Service, you are allowing us to  pass  your  log-in  information  to  these  service  providers  for  this  purpose.  For  more information about the implications of activating these third party services and Thriftmark’s use, storage and disclosure of information related to you and your use of such services within the  Service  (including  your  friend  lists  and  the  like),  please  see  our  Privacy  Policy at <a href="https://thriftmark.in/privacy">https://thriftmark.in/privacy</a>. However, please remember that the manner in which third party services use, store and disclose your information is governed solely by the policies of such  third  parties,  and  Thriftmark  shall  have  no  liability  or  responsibility  for  the  privacy practices or other actions of any third party site or service that may be enabled within the Service.</p>
        <p className="text-gray-700 mb-4">In addition, Thriftmark is not responsible for the accuracy, availability or reliability of any information,  content,  goods,  data,  opinions,  advice  or  statements  made  available  in connection with third party services. As such, Thriftmark is not liable for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such third party service. Thriftmark enables these features merely as a convenience and the inclusion of such features does not imply an endorsement or recommendation.</p>
        <p className="text-gray-700 mb-4"><b>Your  Registration  Obligations:</b> You  may  also  be  permitted  to  register  with  the  Service directly. In any case, if you choose to register for the Service (whether directly or through a third party service), you agree to provide and maintain true, accurate, current and complete information about yourself. Registration data and certain other information about you are governed  by  our <a href="https://thriftmark.in/privacy">Privacy  Policy</a>.  The  Service  is  available  only  to  individuals  who  can  form legally binding contracts under applicable law. Without limiting the foregoing, the Service is not  available  to  minors  (people  under  the  age  of  majority  in  their  state  or  province  of residence) or to temporarily or permanently suspended members of the Service. If you do not qualify, please do not use the Service. Additionally, Thriftmark reserves the right to refuse access to, or use of the Service to anyone, and may terminate any account, at any time, in its sole discretion. You are only authorized to create and use one account for the Service and are prohibited from using alter egos or other disguised identities when using the Service.</p>
        <p className="text-gray-700 mb-4"><b>Member  Account,  Password  and  Security:</b> You  are  responsible  for  maintaining  the confidentiality of your password and account, if any, and are fully responsible for any and all activities that occur under your password or account. You agree to (a) immediately notify Thriftmark  of  any  unauthorized  use  of  your  password  or  account  or  any  other  breach  of security, and (b) ensure that you exit from your account at the end of each session when accessing the Service. Thriftmark will not be liable for any loss or damage arising from your failure to comply with this Section.</p>
        <p className="text-gray-700 mb-4"><b>Modifications to Service:</b> Thriftmark reserves the right to modify or discontinue, temporarily or  permanently,  the  Service  (or  any  part  thereof)  with  or  without  notice.  You  agree  that Thriftmark shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.</p>
        <p className="text-gray-700 mb-4"><b>General  Practices  Regarding  Use  and  Storage:</b>  You  acknowledge  that  Thriftmark  may establish general practices and limits concerning use of the Service. You agree that Thriftmark has no responsibility or liability for the deletion or failure to store any data or other content maintained or transmitted by the Service. You acknowledge that Thriftmark reserves the right to  terminate  accounts  that  are  inactive  for  an  extended  period  of  time.  You  further acknowledge that Thriftmark reserves the right to change these general practices and limits at anytime, in its sole discretion, with or without notice.</p>
        <p className="text-gray-700 mb-4"><b>Mobile Services:</b> When you access the Service through a mobile device, your wireless service carrier’s standard charges, data rates and other fees may apply. In addition, downloading, installing, or using certain mobile services may be prohibited or restricted by your carrier, and not all mobile services may work with all carriers or devices. You acknowledge and agree that your use of the Service must be in accordance with the usage rules established by your mobile device platform or service provider.</p>
        <p className="text-gray-700 mb-4"><b>Friend Referral Program:</b> Thriftmark may from time to time offer discount coupons to existing users that refer new users to the Service using the invite code provided by Thriftmark to such existing users. Thriftmark may also make certain discount coupons available to such new users using that invite code. The amount and requirements to earn such discount coupons will be determined,  and  may  change,  from  time  to  time  in  Thriftmark’s  sole  discretion  and  such program may be terminated by Thriftmark at any time, in each case with or without notice to you.  Furthermore,  Thriftmark  reserves  the  right  to  limit  the  number  and/or  amount  of discount coupons that may be earned with respect to any existing user with or without notice to you. To be eligible for a discount coupon (whether granted to an existing user or new user),the new user must be an individual that has never registered for the Service and must be using a device (not the web) for sign-up and the device being used must not be associated with an existing Thriftmark account. You agree that any discount coupon granted: (1) cannot be traded for cash or any other service; (2) may not be sold or transferred in any manner, or made available to the general public (whether posted to a public forum or otherwise), unless expressly permitted by Thriftmark; (3) cannot be acquired via public distribution where you are a contributor but not the primary content owner (e.g. coupon websites); (4) may expire prior to your use; (5) may be voided or deducted by Thriftmark at any time for any reason without liability to Thriftmark, if Thriftmark believes in its sole discretion that such discount coupons resulted from fraud or other misuse of the Referral program or the Service. If your account has been suspended (see “Termination” below), you will not be able to use such discount coupons during the duration of your account suspension.</p>    

        <h3 className="text-[#535BA3] font-semibold mt-5 mb-2 text-xl md:text-3xl">CONDITIONS OF USE</h3>
        <p className="text-gray-700 mb-4">User  Conduct: You  are  solely  responsible  for  all  descriptions,  pictures  of  items,  listings, information, data, text, software, music, sound, graphics, video, messages or other materials (“content”)  that  you  upload,  post,  publish  or  display  (hereinafter,  “post”)  or  otherwise transmit  via  the  Service,  and  for  all  items  that  you  sell  or  purchase  via  the  Service.  The following are examples of the kind of items, content and/or use that is illegal or prohibited by Thriftmark.  Thriftmark  reserves  the  right  to  investigate  and  take  appropriate  legal  action against anyone who, in Thriftmark’s sole discretion, violates this provision, including withoutlimitation,  removing  the  offending  items  or  content  from  the  Service,  suspending  or terminating  the  account  of  such  violators  and  reporting  you  to  the  law  enforcement authorities. You agree to not use the Service to:</p>
          <ul className="list-decimal list-inside text-gray-700 mb-4">
              <li>sell,  post  or  otherwise  transmit  any  item  or  content  that  (i)  is  unlawful,  harmful, threatening,  abusive,  harassing,  tortious,  excessively  violent,  defamatory,  vulgar, obscene,  pornographic,  libellous,  invasive  of  another‘s  privacy,  hateful  racially, ethnically or otherwise objectionable; (ii) you do not have a right to sell or transmit under any law or under contractual or fiduciary relationships; (iii) poses or creates a privacy or security risk to any person; (iv) infringes any intellectual property or other proprietary rights of any party; (v) constitutes unsolicited or unauthorized advertising, promotional materials, commercial activities and/or sales, “junk mail,” “spam,” “chain letters,”  “pyramid  schemes,”  “contests,”  “sweepstakes,”  or  any  other  form  of solicitation;  (vi)  contains  software  viruses  or  any  other  computer  code,  files  or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; or (vii) in the sole judgment of Thriftmark, is objectionable or which restricts or inhibits any other person from using or enjoying the Service, or which may expose Thriftmark or its users to any harm or liability of any type;</li>
              <li>impersonate  any  person  or  entity,  or  falsely  state  or  otherwise  misrepresent  your affiliation with a person or entity;</li>
              <li>solicit personal information from anyone under the age of 18;</li>
              <li>harvest or collect email addresses or other contact information of other users from the  Service  or  the  Site  by  electronic  or  other  means  for  the  purposes  of  sending unsolicited emails or other unsolicited communications;</li>
              <li>advertise or offer to sell or buy any goods or services other than those items intended to be sold and purchased through the Service; </li>
              <li>interfere with or disrupt the Service or servers or networks connected to the Service, or  disobey  any  requirements,  procedures,  policies  or  regulations  of  networks connected to the Service; or</li>
              <li>violate any applicable local, state, national or international law, or any regulations having the force of law;</li>
              <li>engage  in  any  activities  that  violate  any  consumer  protection,  anti-spam,  data protection, or privacy egislation in any jurisdiction;</li>
              <li>further  or  promote  any  criminal  activity  or  enterprise  or  provide  instructional information about illegal activities; or</li>
              <li>obtain or attempt to access or otherwise obtain any materials or information through any means not intentionally made available or provided for through the Service</li>
          </ul>
        <p className="text-gray-700 mb-4">Thriftmark may provide required fields to comply with Sellers obligations under metrology laws. Sellers are responsible for the accuracy of key metrology items such as country of origin, manufacturer name, sizing information and any other relevant details that enable purchasers to  make  informed  decisions  prior  to  making  a  purchase  in  accordance  with  the  Legal Metrology Act and Consumer Protection Rules. The ultimate responsibility is on the Seller to correctly identify their items in accordance with all local laws and regulations.</p>
        
        <h3 className="text-[#535BA3] font-semibold mt-5 mb-2 text-xl md:text-3xl">PURCHASE AND SALE TRANSACTIONS</h3>
        <p className="text-gray-700 mb-4"><b>Fees:</b> Registering for the Service is free; however, Thriftmark charges certain fees for various transactions effected through the Service, as set forth in the Fee Policy. Unless otherwise stated, all fees are quoted in Indian Rupees.</p>
        <p className="text-gray-700 mb-4">While listing Items on the platform, it is the Seller’s responsibility to specify the correct weight category.  In  case  of  under-reporting  of  weight,  Thriftmark  reserves  the  right  to  deduct additional shipping charges from the Seller as per the Fee policy.</p>
        <p className="text-gray-700 mb-4">Thriftmark also reserves the right to hold the shipment till the time either buyer or seller pay the additional shipping charges and the penalty levied by Thriftmark. In case of non-receipt of due within 15 days, Thriftmark can liquidate the shipment goods to recover the shipping charges and penalties.</p>
        <p className="text-gray-700 mb-4"><b>Taxes; Shipping Costs; Buyer Responsibility:</b> Items purchased by and shipped to Buyers in locations across India may be subject to applicable state, provincial or local sales or use tax,privilege tax or similar transaction-based taxes (“State Tax”). The amount of Taxes is based on a number of factors, including but not limited to the type of Items purchased, the Buyers designated delivery address, and/or the location of the Seller. </p>
        <p className="text-gray-700 mb-4">Buyers are responsible for paying the applicable purchase price for a purchased Item to the Seller, as well as any shipping costs (which are detailed in the Fee Policy) and paying applicable Taxes and/or duties associated with the purchase and sale of any Items through the Service.</p>
        <p className="text-gray-700 mb-4">Buyers  may  use  certain  Thriftmark  promotions  or  credits,  including  credits  in  a  Seller’s account, towards the purchase of Items. Depending on the type of promotion or credit used, it  may  reduce  the  amount  of  Taxes  that  apply  to  a  Buyer’s  order.  The  application  of  the promotion or credit will be reflected at the time of checkout and on the receipt of purchase. </p>
        <p className="text-gray-700 mb-4">Tax  and  shipping  costs  are  not  included  in  the  listed  price  for  any  Items  listed  by  Sellers through the Service but will be displayed to Buyers before confirmation of any purchase.</p>
        <p className="text-gray-700 mb-4"><b>Marketplace Collection; Taxes; Commissions; Seller Responsibility:</b> Thriftmark  will  collect Taxes from Buyers on behalf of Sellers where we are legally obligated to do so, including (1) those states that have enacted legislation requiring marketplaces, like Thriftmark, to collect Taxes, and (2) those states that have agreed to allow Thriftmark to collect Taxes on behalf of Sellers. In these states, the amount of Taxes collected will be submitted by Thriftmark to the appropriate taxing authority on behalf of Sellers. In those states where Thriftmark does not collect Taxes on behalf of Sellers, Sellers are responsible for collecting and submitting any Taxes to the appropriate taxing authority in accordance with relevant state or local tax laws.</p>
        <p className="text-gray-700 mb-4">Sellers are responsible for paying all taxes imposed or measured by Seller’s net income, net profits, income, profits, and/or revenues associated with the sale of any Items through the Service.</p>
        <p className="text-gray-700 mb-4"><b>Payments:</b> Buyers may pay for Items using UPI, debit card, credit card, or other payment methods. If you submit your payment information through the Service, then you authorize Thriftmark to store that payment information and charge your payment method for any Item you purchase.</p>
        <p className="text-gray-700 mb-4"><b>Fee  Modifications:</b> We  reserve  the  right  to  change  or  discontinue,  temporarily  or permanently, some or all of the fees for the Service. Any change will be effective upon posting of a revised Fee Policy.</p>
        <p className="text-gray-700 mb-4"><b>Marketplace  Risk:</b> Thriftmark  is  not  affiliated  with  or  endorsed  by  any  designer, manufacturer, retailer or brand of the Items made available through the Service. Thriftmark is a marketplace and technology platform and is not involved in any transaction between Buyers and Sellers, does not obtain title to any purchased Items and does not act as a Buyer, Seller (or affiliate for a Buyer or Seller) or broker with respect to any transactions. There are risks that you assume when dealing with other users (including those who may be acting under  false  pretenses)  and  all  of  these  risks  are  borne  by  you,  and  not  Thriftmark.  We encourage you to use the various functionalities of the Service (e.g., our Item commenting system and seller reviews) to help evaluate the user with whom you are dealing. </p>
        <p className="text-gray-700 mb-4">Thriftmark does not control the behavior of users of the Service or the information or User Content (defined below) provided by other users. As a result, Thriftmark does not guarantee or endorse the authenticity, quality, safety, or legality of any Items offered or sold, the truth or accuracy of any listings, or the ability of Sellers to sell Items or of Buyers to buy Items. We cannot  assure  that  all  transactions  will  be  completed.  Additionally,  Thriftmark  does  not guarantee  the  ability  or  intent  of  users  to  fulfill  their  obligations  in  any  transactions. Thriftmark reserves the right to delay the completion of any transaction for a reasonable period of time for purposes of fraud detection and otherwise protecting Thriftmark and its users from illegal or wrongful activities or other violations of these Terms. </p>
        <p className="text-gray-700 mb-4 font-bold">FOR  EVERY  TRANSACTION  THAT  IS  COMMENCED  THROUGH  THE  SERVICE,  YOU  MUST MAKE YOUR  OWN  INDEPENDENT  DETERMINATION  REGARDING  THE  STATEMENTS, DESCRIPTIONS OR THE SELLER’S REPRESENTATIONS AND THE BUYER’S ABILITY TO PAY FOROR DELIVER THE ITEM(S) OFFERED. PLEASE USE CAUTION, COMMON SENSE, AND PRACTICE SAFE TRADING WHEN DEALING WITH OTHER USERS OR OTHERWISE USING THE SERVICE.</p>
        <p className="text-gray-700 mb-4"><b>Prohibited Items:</b> Thriftmark prohibits the listing or sale of any Item that is illegal to sell under any applicable law, statute, ordinance, or regulation. </p>
        <p className="text-gray-700 mb-4"><b>Sellers:</b> You must have the right to sell the Items that you make available for sale through the Service. You must describe your Item (including the original price) and all terms of sale in your listing truthfully, accurately and completely. </p>
        <p className="text-gray-700 mb-4"><b>Buyers:</b> You are responsible for reading the full Item listing before making an offer. When you make an offer and your offer is accepted by the Seller, you have a contract with the Seller. </p>
        <p className="text-gray-700 mb-4">Thriftmark will provide Seller with prepaid shipping labels (“Label”). Seller can print Labels from a webpage generated by Thriftmark.</p>
        <p className="text-gray-700 mb-4">Seller must ship the Item to the Buyer using the Label (and corresponding shipping method) within 3 days after Buyer pays the amount for the Item. If the Seller does not ship the Item within that time period, then we will notify Seller and give Seller a set amount of time to ship the Item before we cancel the order automatically. Seller transfers title to the Item upon shipment.  Once  the  Item  is  shipped,  Thriftmark’s  obligations  for  that  sale  are  complete. Notwithstanding the foregoing, a Buyer may cancel an order for an Item before the Item is shipped.</p>
        <p className="text-gray-700 mb-4">When  using  a  Label  provided  by  Thriftmark:  (i)  Seller  may  only  use  the  Label  to  ship  the applicable Item; (ii) Labels may not be transferred or sold to a third party; (iii) Seller is fully responsible  for  the  contents  of  any  parcels  shipped  using  the  Label;  and  (iv)  Seller  must comply with the terms and conditions and any other policies or rules imposed by the carrier used to ship the Items. As a Buyer, if an Item shipped with a Label is lost, damaged, or arrives later than expected, or is the wrong Item, we have no obligation to you; however, please report the issue to us through the Service within three days after delivery. Thriftmark reserves the right to discontinue providing Labels to any or all users at any time and for any reason.</p>
        <p className="text-gray-700 mb-4">Once  the  Buyer  confirms  it  has  received  and  accepted  the  Item  (either  by  affirmatively indicating acceptance through the Service or by failing to notify Thriftmark of any issues with the Item at the time of delivery of the Item, as determined by the tracking information), then Thriftmark will credit the Seller with an amount equal to the payment received from the Buyer (less any applicable Tax), minus Thriftmark’s commission, as set forth in the Fee Policy.</p>
        <p className="text-gray-700 mb-4"><b>Returns:</b> Thriftmark may allow you to return an Item in limited circumstances. If the Item you receive is not as described on the Service, then you may request a return by reporting the issue through the Service or by emailing admin@thriftmark.in, in each case within three days after delivery (as determined by the tracking information) of the Item. In case of no proved deviation from description of product, Buyer can choose to return Item to seller at their own cost.</p>
        <p className="text-gray-700 mb-4"><b>Penalty:</b> In case of violation of any terms by users, Thriftmark reserves the right to levy the penalty as deemed fit. </p>

        <h3 className="text-[#535BA3] font-semibold mt-5 mb-2 text-xl md:text-3xl">INTELLECTUAL PROPERTY RIGHTS</h3>
        <p className="text-gray-700 mb-4"><b>Service Content, Software and Trademarks:</b> You acknowledge and agree that the Service may contain  images  and  descriptions  of  fashion,  home,  electronics  items  and  other  content (collectively,  “Service  Content”)  that  is  protected  by  copyright,  patent,  trademark,  trade secret or other proprietary rights and laws. Except as expressly authorized by Thriftmark, you agree not to modify, copy, frame, scrape, rent, lease, loan, sell, distribute or create derivative works  based  on  the  Service  or  the  Service  Content,  in  whole  or  in  part,  except  that  the foregoing does not apply to your own User Content (as defined below) that you legally upload to the Service. In connection with your use of the Service you shall not engage in or use any data mining, robots, scraping or similar data gathering or extraction methods. Any use of the Service  or  the  Service  Content  other  than  as  specifically  authorized  herein  is  strictly prohibited.  The  technology  underlying  the  Service  (including  the  Software  distributed  in connection therewith) is the property of Thriftmark, our affiliates and our partners. You agree not  to  copy,  modify,  create  a  derivative  work  of,  reverse  engineer,  reverse  assemble  or otherwise attempt to discover any source code, sell, assign, sublicense, or otherwise transfer any right in the Service (including the Software). Any rights not expressly granted herein are reserved by Thriftmark. </p>
        <p className="text-gray-700 mb-4">The Thriftmark name and logos are trademarks and service marks of Thriftmark (collectively the “Thriftmark Trademarks”). Other company, product, and service names and logos used and displayed via the Service may be trademarks or service marks of their respective owners who may or may not endorse or be affiliated with or connected to Thriftmark. Nothing in these  Terms  or  the  Service  should  be  construed  as  granting,  by  implication,  estoppel,  or otherwise, any license or right to use any of Thriftmark Trademarks displayed on the Service, without our prior written permission in each instance. All goodwill generated from the use of Thriftmark Trademarks will inure to our exclusive benefit.</p>
        <p className="text-gray-700 mb-4"><b>Electronic  Communications:</b> When  you  use  the  Service  or  send  e-mails  to  us,  you  are communicating with us electronically. We will communicate with you by e-mail or providing notices  via  the  Service.  You  agree  that  all  agreements,  notices,  disclosures  and  other communications that we provide to you electronically satisfy any legal requirement that such communications  be  in  writing.  Any  such  emails  may  include  marketing  and  promotional content.</p>
        <p className="text-gray-700 mb-4"><b>Third Party Material:</b> Under no circumstances will Thriftmark be liable in any way for any items or content posted by third parties or at the direction of users, including, but not limited to, for any errors or omissions in any content, or for any loss or damage of any kind incurred as a result of the use of any items or content posted, sold, purchased or otherwise transmitted via the Service. You acknowledge that Thriftmark does not pre-screen items or content, but that Thriftmark and its designees shall have the right (but not the obligation) in their sole discretion to refuse or remove any items or content that is available via the Service. Without limiting the foregoing, Thriftmark and its designees shall have the right to remove any item or content that violates these Terms or is deemed by Thriftmark, in its sole discretion, to be otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any items or content, including any reliance on the safety, condition, accuracy, completeness, or usefulness of such items or content. </p>
        <p className="text-gray-700 mb-4"><b>User Content Posted on the Site:</b> You  are  solely  responsible  for  the  content  you  post  or transmit  on  or  through  the  Service  (collectively,  “User  Content”).  You  will  not  post  any content that you did not create or that you do not own all right, title and interest in and to, including, without limitation, all copyright and rights of publicity contained therein. By posting or otherwise transmitting any User Content you hereby grant and will grant to Thriftmark and its affiliated companies a nonexclusive, worldwide, royalty free, fully paid up, transferable, sublicenseable, perpetual, irrevocable license to copy, display, transmit, perform, distribute, store, modify, make derivative works of and otherwise use in any manner your User Content in  connection  with  the  operation  of  the  Service  or  any  other  products  or  services  of Thriftmark,  or  the  promotion,  advertising  or  marketing  thereof,  in  any  form,  medium  or technology now known or later developed (including without limitation publishing your User Content on the Internet or on Third Party Services such as Facebook, sharing it with blogs, etc., and allowing other users to share listings that include your User Content).</p>
        <p className="text-gray-700 mb-4">You acknowledge and agree that any questions, comments, suggestions, ideas, feedback or other  information  about  the  Site  or  the  Service  (“Submissions”),  provided  by  you  to Thriftmark are non-confidential and Thriftmark shall be entitled to the unrestricted use and dissemination  of  these  Submissions  for  any  purpose,  commercial  or  otherwise,  without acknowledgment or compensation to you.</p>
        <p className="text-gray-700 mb-4">You  acknowledge  and  agree  that  Thriftmark  may  preserve  content  and  may  also  disclose content  if  required  to  do  so  by  law  or  in  the  good  faith  belief  that  such  preservation  or disclosure  is  reasonably  necessary  to:  (a)  comply  with  legal  process,  applicable  laws  or government requests; (b) enforce these Terms; (c) respond to claims that any content violates the rights of third parties; or (d) protect the rights, property, or personal safety of Thriftmark, its users and the public. You understand that the technical processing and transmission of theService, including your content, may involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.</p>
        <p className="text-gray-700 mb-4"><b>Infringement Policy:</b> Thriftmark respects the intellectual property of others, and we ask our users to do the same. Thriftmark will promptly process and investigate notices of alleged infringement and will take appropriate actions under the Copyright Act and other applicable intellectual property laws with respect to any alleged or actual infringement. If you believe that your work has been copied in a way that constitutes copyright infringement, or that your intellectual property rights have been otherwise violated, please provide our Copyright Agent with the following information:</p>
          <ul className="list-disc list-inside text-gray-700 mb-4">
              <li>an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest; </li>
              <li>a description of the copyrighted work or other intellectual property that you claim has been infringed; </li>
              <li>a  description  of  where  the  material  that  you  claim  is  infringing  is  located  on  the Service, with enough detail that we may find it on the Service; </li>
              <li>your address, telephone number, and email address; </li>
              <li>a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright or intellectual property owner, its agent, or the law; </li>
              <li>a statement by you, made under penalty of perjury, that the above information in your Notice is accurate and that you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner’s</li>
          </ul>

          <p className="text-gray-700 mb-4">If you believe that your User Content that was removed (or to which access was disabled) is not infringing, or that you have the authorization from the copyright owner, the copyright owner’s agent, or pursuant to the law, to post and use the content in your User Content, you may  send  a  written  counter-notice  containing  the  following  information  to  the  Copyright Agent:</p>
          <ul className="list-disc list-inside text-gray-700 mb-4">
                <li>your physical or electronic signature;</li>
                <li>identification  of  the  content  that  has  been  removed  or  to  which  access  has  been disabled and the location at which thecontent appeared before it was removed or disabled;</li>
                <li>a  statement  that  you  have  a  good  faith  belief  that  the  content  was  removed  or disabled as a result of mistake or amisidentification of the content; and </li>
                <li>your  name,  address,  telephone  number,  and  email  address,  a  statement  that  you consent  to  the  jurisdiction  of  the  high  court  and  a  statement  that  you  will  accept service  of  process  from  the  person  who  provided  notification  of  the  alleged infringement.</li>
            </ul>
          <p className="text-gray-700 mb-4">If a counter-notice is received by the Copyright Agent, Thriftmark will send a copy of the counter-notice to the original complaining party informing that person that it may replace the removed content or cease disabling it in 10 business days. Unless the copyright owner files an action seeking a court order against the content provider, member or user, the removed content may be replaced, or access to it restored, in 10 to 14 business days or more after receipt of the counter-notice, at our sole discretion.</p>
          <p className="text-gray-700 mb-4">The above information should be sent to Thriftmark’s Copyright Agent for Notice of claims of copyright  or  other  intellectual  property  infringement  by  email  to  the  following  address: <a href="mailto:admin@thriftmark.in">admin@thriftmark.in</a></p>

        <h3 className="text-[#535BA3] font-semibold mt-5 mb-2 text-xl md:text-3xl">THIRD PARTY WEBSITES</h3>
        <p className="text-gray-700 mb-4">The Service may provide, or third parties may provide, links or other access to other sites and resources  on  the  Internet.  Thriftmark  has  no  control  over  such  sites  and  resources  and Thriftmark is not responsible for and does not endorse such sites and resources. You further acknowledge and agree that Thriftmark shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any content, events, goods or services available on or through any such site or resource. Any dealings you have with third parties found while using the Service are between you and the third party, and you agree that Thriftmark is not liable for any loss or claim that you may have against any such third party. </p>

        <h3 className="text-[#535BA3] font-semibold mt-5 mb-2 text-xl md:text-3xl">INDEMNITY AND RELEASE</h3>
        <p className="text-gray-700 mb-4">You  agree  to  release,  indemnify  and  hold  Thriftmark  and  its  affiliates  and  their  officers, employees, directors and agents (collectively,”Indemnitees”) harmless from any from any and all losses, damages, expenses, including reasonable attorneys’ fees, rights, claims, actions of any  kind  and  injury  (including  death)  arising  out  of  or  relating  to  your  use  of  the  Service (including any sale or purchase of any items through the Service), any User Content, your connection to the Service, your violation of these Terms or your violation of any rights of another. Notwithstanding the foregoing, you will have no obligation to indemnify or hold harmless any Indemnitee from or against any liability, losses, damages or expenses incurred as a result of any action or inaction of such Indemnitee.</p>

        <h3 className="text-[#535BA3] font-semibold mt-5 mb-2 text-xl md:text-3xl">DISCLAIMER OF WARRANTIES</h3>
        <p className="text-gray-700 mb-4">YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. THRIFTMARK EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT.</p>
        <p className="text-gray-700 mb-4">THRIFTMARK MAKES NO WARRANTY THAT (I) YOU WILL BE ABLE TO SELL OR PURCHASE ANY ITEMS  THROUGH  THE  SERVICE  OR  THAT  THE  SERVICE  WILL  OTHERWISE  MEET  YOUR REQUIREMENTS, (II) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (III) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, OR (IV) THE QUALITY OF ANY GOODS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS.</p>

        <h3 className="text-[#535BA3] font-semibold mt-5 mb-2 text-xl md:text-3xl">LIMITATION OF LIABILITY</h3>
        <p className="text-gray-700 mb-4">YOU EXPRESSLY UNDERSTAND AND AGREE THAT THRIFTMARK SHALL NOT BE LIABLE FOR ANY INDIRECT,INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY DAMAGES, OR DAMAGES FOR LOSS OF PROFITS INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF GOODWILL, USE, DATA  OR  OTHER  INTANGIBLE  LOSSES  (EVEN  IF  THRIFTMARK  HAS  BEEN  ADVISED  OF  THE POSSIBILITY  OF  SUCH  DAMAGES),  WHETHER  BASED  ON  CONTRACT,  TORT,  NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, RESULTING FROM: (I) THE USE OR THE INABILITY TO USE THE SERVICE (INCLUDING ANY INJURY OR OTHER BODILY HARM THAT MAY RESULT FROM YOUR USE OF THE SERVICE); (II) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED ORTRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICE; (III) UNAUTHORIZED ACCESS TO ORALTERATION OF YOUR TRANSMISSIONS OR DATA; (IV) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; OR (V) ANY OTHER  MATTER  RELATING  TO  THE  SERVICE.  IN  NO  EVENT  SHALL  THRIFTMARK’S  TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES OR CAUSES OF ACTION EXCEED THE AMOUNT OF COMMISSIONS THAT YOU HAVE PAID TO THRIFTMARK AS A SELLER IN THE LAST SIX (6) MONTHS, OR, IF GREATER, TWO THOUSAND INDIAN RUPEES (INR 2000). </p>
        <p className="text-gray-700 mb-4">SOME  JURISDICTIONS  DO  NOT  ALLOW  THE  DISCLAIMER  OR  EXCLUSION  OF  CERTAIN WARRANTIES  OR  THELIMITATION  OR  EXCLUSION  OF  LIABILITY  FOR  INCIDENTAL  OR CONSEQUENTIAL DAMAGES. ACCORDINGLY,SOME OF THE ABOVE LIMITATIONS SET FORTH ABOVE MAY NOT APPLY TO YOU OR BE ENFORCEABLE WITH RESPECT TO YOU. IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE SERVICE OR WITH THESE TERMS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USE OF THE SERVICE.</p>
        
        <h3 className="text-[#535BA3] font-semibold mt-5 mb-2 text-xl md:text-3xl">DISPUTE RESOLUTION BY BINDING ARBITRATION</h3>
        <p className="text-gray-700 font-bold mb-4">PLEASE READ THIS SECTION CAREFULLY AS IT AFFECTS YOUR RIGHTS.</p>
          <ul class="list-decimal list-inside text-gray-700 mb-4">
            <li><b>Agreement to Arbitrate</b>
                <ul class="list-none list-inside mb-4">
                    <li>This Dispute Resolution by Binding Arbitration section is referred to in these Terms as the “Arbitration Agreement.” You agree that any and all disputes or claims that have arisen or may arise between you and Thriftmark, whether arising out of or relating to these Terms of Service (including any alleged breach thereof), the Services, any advertising, any aspect of the relationship or transactions between us, shall be resolved exclusively through final and binding arbitration, rather than a court, in accordance with the terms of this Arbitration Agreement, except that you may assert individual claims in small claims court, if your claims qualify. Further, this Arbitration Agreement does not preclude you from bringing issues to the attention of federal, state, provincial or local agencies, and such agencies can, if the law allows, seek relief against us on your behalf. You agree that, by entering into these Terms, you and Thriftmark are each waiving the right to a trial by jury or to participate in a class action. Your rights will be determined by a neutral arbitrator, not a judge or jury.</li>
                </ul>
            </li>
            <li><b>Prohibition of Class and Representative Actions and Non-Individualized Relief</b>
                <ul class="list-none list-inside mb-4">
                    <li>You and Company agree that each of us may bring claims against the other only on an individual basis and not as a plaintiff or class member in any purported class or representative action or proceeding. Unless both you and Company agree otherwise, the arbitrator may not consolidate or join more than one person’s or party’s claims and may not otherwise preside over any form of a consolidated, representative, or class proceeding. Also, the arbitrator may award relief (including monetary, injunctive, and declaratory relief) only in favor of the individual party seeking relief and only to the extent necessary to provide relief necessitated by that party’s individual claim(s).</li>
                </ul>
            </li>
            <li><b>Pre-Arbitration Dispute Resolution</b>
                <ul class="list-none list-inside mb-4">
                    <li>Thriftmark is always interested in resolving disputes amicably and efficiently, and most customer concerns can be resolved quickly and to the customer’s satisfaction by emailing customer support at <a href="mailto:admin@thriftmark.in">admin@thriftmark.in</a>. If such efforts prove unsuccessful, a party who intends to seek arbitration must first send to the other, by certified mail, a written Notice of Dispute(“Notice”). The Notice must (i) describe the nature and basis of the claim or dispute and (ii) set forth the specific relief sought. If Thriftmark and you do not resolve the claim within sixty (60) calendar days after the Notice is received, you or Thriftmark may commence an arbitration proceeding. During the arbitration, the amount of any settlement offer made by Thriftmark or you shall not be disclosed to the arbitrator until after the arbitrator determines the amount, if any, to which you or Thriftmark is entitled. </li>
                </ul>
            </li>
            <li><b>Arbitration Procedures</b>
                <ul class="list-none list-inside mb-4">
                    <li>Arbitration will be conducted by a neutral arbitrator in accordance with the rules and procedures in the Arbitration and Conciliation Act. Although arbitration proceedings are usually simpler and more streamlined than trials and other judicial proceedings, the arbitrator can award the same damages and relief on an individual basis that a court can award to an individual under the Terms of Service and applicable law. Decisions by the arbitrator are enforceable in court and may be overturned by a court only for very limited reasons.
                      <br></br><br></br>Unless Thriftmark and you agree otherwise, any arbitration hearings will take place in a reasonably convenient location for both parties with due consideration of their ability to travel and other pertinent circumstances. Regardless of the manner in which the arbitration is conducted, the arbitrator shall issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the award is based.  </li>
                </ul>
            </li>
            <li><b>Costs of Arbitration</b>
                <ul class="list-none list-inside mb-4">
                    <li>Payment of all filing, administration, and arbitrator fees (collectively, the “Arbitration Fees”) will be governed by the Act. If the arbitrator determines for any reason that you should not be required to pay your portion of the Arbitration Fees, Thriftmark will pay your portion of such fees. In addition, if you demonstrate to the arbitrator that the costs of arbitration will be prohibitive as compared to the costs of litigation, Thriftmark will pay as much of the Arbitration Fees as the arbitrator deems necessary to prevent the arbitration from being cost-prohibitive.</li>
                </ul>
            </li>
            <li><b>Confidentiality</b>
                <ul class="list-none list-inside mb-4">
                    <li>All aspects of the arbitration proceeding, and any ruling, decision, or award by the arbitrator, will be strictly confidential for the benefit of all parties.</li>
                </ul>
            </li>
            <li><b>Severability</b>
                <ul class="list-none list-inside mb-4">
                    <li>If a court or the arbitrator decides that any term or provision of this Arbitration Agreement (other than the subsection (b)titled “Prohibition of Class and Representative Actions and Non-Individualized Relief” above) is invalid or unenforceable, the parties agree to replace such term or provision with a term or provision that is valid and enforceable and that comes closest to expressing the intention of the invalid or unenforceable term or provision, and this Arbitration Agreement shall be enforceable as so modified. If a court or the arbitrator decides that any of the provisions of subsection (b) above titled “Prohibition of Class and Representative Actions and Non-Individualized Relief” are invalid or unenforceable, then the entirety of this Arbitration Agreement shall be null and void. The remainder of the Terms of Service will continue to apply.</li>
                </ul>
            </li>
            <li><b>Future Changes to Arbitration Agreement</b>
                <ul class="list-none list-inside mb-4">
                    <li>Notwithstanding any provision in these Terms of Service to the contrary, Thriftmark agrees that if it makes any future change to this Arbitration Agreement (other than a change to the Notice Address) while you are a user of the Services, you may reject any such change by sending Thriftmark written notice within thirty (30) calendar days of the change to the Notice Address provided above. By rejecting any future change, you are agreeing that you will arbitrate any dispute between us in accordance with the language of this Arbitration Agreement as of the date you first accepted these Terms of Service (or accepted any subsequent changes to these Terms of Service).</li>
                </ul>
            </li>
        </ul>

        <h3 className="text-[#535BA3] font-semibold mt-5 mb-2 text-xl md:text-3xl">TERMINATION</h3>
        <p className="text-gray-700 mb-4">You agree that Thriftmark, in its sole discretion, may suspend or terminate your account (or any part thereof) or use of the Service and remove and discard any items or content within the  Service,  for  any  reason,  including,  without  limitation,  for  lack  of  use  or  if  Thriftmark believes that you have violated or acted inconsistently with the letter or spirit of these Terms. Any suspected fraudulent, abusive or illegal activity that may be grounds for termination of your use of Service, may be referred to appropriate law enforcement authorities. Thriftmark may also in its sole discretion and at any time discontinue providing the Service, or any part thereof, with or without notice. You agree that any termination of your access to the Service under any provision of these Terms may be effected without prior notice, and acknowledge and agree that Thriftmark may immediately deactivate or delete your account and all related information and files in your account and/or bar any further access to such files or the Service. Further,  you  agree  that  Thriftmark  shall  not  be  liable  to  you  or  any  third-party  for  any termination of your access to the Service.</p>
        
        <h3 className="text-[#535BA3] font-semibold mt-5 mb-2 text-xl md:text-3xl">USER DISPUTES</h3>
        <p className="text-gray-700 mb-4">You agree that you are solely responsible for your interactions (including any purchase and sale transactions) with any other user in connection with the Service and Thriftmark will have no liability or responsibility with respect thereto. Thriftmark reserves the right, but has no obligation, to become involved in any way with disputes between you and any other user of the Service.</p>
        
        <h3 className="text-[#535BA3] font-semibold mt-5 mb-2 text-xl md:text-3xl">GENERAL</h3>
        <p className="text-gray-700 mb-4">These Terms constitute the entire agreement between you and Thriftmark and govern your use  of  the  Service,  superseding  any  prior  agreements  between  you  and  Thriftmark  with respect to the Service. You also may be subject to additional terms and conditions that may apply  when  you  use  affiliate  or  third-party  services,  third-party  content  or  third-party software. With respect to any disputes or claims not subject to arbitration, as set forth above, you and Thriftmark agree to submit to the personal and exclusive jurisdiction of the state and federal courts located within Kolkata, West Bengal. The failure of Thriftmark to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision.  If  any  provision  of  these  Terms  of  Service  is  found  by  a  court  of  competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in the provision, and the other provisions of these Terms of Service remain in full force and effect. You agree that regardless of any statute or law to the contrary, to the fullest extent permitted by applicable law, any claim or cause of action arising out of or related to use of the Service or these Terms of Service must be filed within one (1) year (unless applicable law provides for a longer period) after such claim or cause of action arose or be forever barred. <u>This electronic document, and all other electronic documents referred to or incorporated herein, will be: (a) deemed for all purposes to be a “writing”  or  “in  writing”,  and  to  comply  with  all statutory,  contractual,  and  other  legal requirements  for  a  writing;  and  (b)  legally  enforceable  as  a signed  agreement.</u> A  printed version of this agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. The section titles in these Terms of Service are for convenience only and have no legal or contractual effect. Notices to you may be made via either email or regular mail. The Service may also provide notices to you of changes to these Terms of Service or other matters by displaying notices or links to notices generally on the Service.</p>
        
        <h3 className="text-[#535BA3] font-semibold mt-5 mb-2 text-xl md:text-3xl">YOUR PRIVACY</h3>
        <p className="text-gray-700 mb-4">At Thriftmark, we respect the privacy of our users. For details please see our <a href="https://thriftmark.in/privacy">Privacy Policy</a>. By  using  the  Service,  you  consent  to  our  collection  and  use  of  personal  data  as  outlined therein.</p>
        
        <h3 className="text-[#535BA3] font-semibold mt-5 mb-2 text-xl md:text-3xl">QUESTIONS & SUGGESTIONS</h3>
        <p className="text-gray-700 mb-4">Please contact us at <a href="mailto:admin@thriftmark.in">admin@thriftmark.in</a> to report any violations of these Terms of Service or to pose any questions regarding these Terms of Service or the Service. </p>
        <p className="text-gray-700 mb-4">Thriftmark Lifestyles Pvt Ltd, Kolkata, West Bengal, India</p>
      </div>
    </div>
  </div>
  </>
);   
}

TermsPage.getLayout = getLayout;