name: Deploy to Broodle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Broodle VM
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      
      
      run: |
        sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no -P 1991 -o User=$SSH_USERNAME -r * $SSH_USERNAME@$SSH_HOST:$DEPLOY_PATH
        sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -p 1991 $SSH_USERNAME@$SSH_HOST "cd $DEPLOY_PATH && yarn"
        sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -p 1991 $SSH_USERNAME@$SSH_HOST "sudo systemctl restart nginx"
